server:
  port: 8080

spring:
  application:
    name: QUERY-SERVICE
  cloud:
    gateway:
      routes:
       - id : DATA-SERVICE
         uri: lb://DATA-SERVICE
         predicates:
            - Path=/api/v1/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://covid-19-service-registry.herokuapp.com/eureka
  instance:
    hostname: covid-19-service-registry.herokuapp.com
