server:
  port: 8080

spring:
  application:
    name: QUERY-SERVICE
  cloud:
    gateway:
      routes:
       - id : DATA-SERVICE
         uri: lb://DATA-SERVICE
         predicates:
            - Path=/api/v1/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost